# Example Site settings

#google_analytics: UA-NNNNNNNN-N

footer: 'contact: sy6kang@gmail.com'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

# 2020-12-08 nav bar setting
# nav bar setting: _data/navigation.yml
# need to make multi-level menu

remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
